CREATE TABLE NEGOCIO(
IdNegocio INT PRIMARY KEY,
Nombre VARCHAR(60),
RFC VARCHAR(60),
Direccion VARCHAR(200),
Logo VARBINARY(MAX) NULL
)

INSERT INTO NEGOCIO (IdNegocio, Nombre, RFC, Direccion)
VALUES (
'1',
'FERRETERA LA BASE',
'VAZK980807PP2',
'CALLE 4 LOCALES 5 Y 6 COL. ICACOS
C.P. 39860 ACAPULCO DE JUAREZ, GRO.'
)

SELECT * FROM NEGOCIO;